#!/bin/sh

set -e

case "$1" in
    configure)
        adduser --system --disabled-password --disabled-login --home /var/empty \
                --no-create-home --quiet --force-badname --group _djapp
        chown _djapp:adm /usr/share/polls/lib/python3.5/site-packages/db.sqlite3
        chown _djapp:adm /var/log/
        # Execute django migration
        /usr/bin/polls-admin django-admin migrate
        ;;
esac

#DEBHELPER#

exit 0